version: "3.9"

services:
  # Our Postgres database
  db: # The service will be named db.
    image: postgres # The postgres image will be used
    restart: always # Always try to restart if this stops running
    environment: # Provide environment variables
      POSTGRES_USER: bon # POSTGRES_USER env var w/ value bon
      POSTGRES_PASSWORD: bon
      POSTGRES_DB: lenslocked
    ports: # Expose ports so that apps not running via docker compose can connect to them.
      - 5433:5432 # format here is "port on our machine":"port on container"
